### ISSUE TITLE
package replaces itself

### ISSUE THREAD

**Issue by Rushi98** [hkuchampudi/Windscribe#6]
(I'm using local "custom" repo for aur packages, aurutils to maintain them).

## Faulty code line :
https://github.com/hkuchampudi/Windscribe/blob/8821a4490a37041b22d417b94a847607f0743e27/PKGBUILD#L16

## Results in 
```bash
:: Replace windscribe-cli with custom/windscribe-cli? [Y/n] 
```
Each time doing `pacman -Syu`. The replace operation eventually fails. 

## Solution:
Delete the line

```patch
diff --git a/PKGBUILD b/PKGBUILD
index 174e2cc..bf5fb77 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -13,7 +13,6 @@ url="https://windscribe.com/"
 license=('GPL-2+')
 depends=('openvpn')
 optdepends=('stunnel')
-replaces=('windscribe-cli')
 install="windscribe-cli.install"
 source_armv6h=("${pkgname}_${pkgver}_${pkgrel}.deb::https://assets.staticnetcontent.com/desktop/linux/windscribe-cli_${pkgver}-${pkgrel}_armhf.deb")
 source_i686=("${pkgname}_${pkgver}_${pkgrel}.deb::https://assets.staticnetcontent.com/desktop/linux/windscribe-cli_${pkgver}-${pkgrel}_i386.deb")
```

**Comment by hkuchampudi** [comment]
@Rushi98 
Thanks for leaving this comment! I have been meaning to make several changes to the PKGBUILD (including the one you mention above), but I have been otherwise preoccupied. 

I have implemented this change (along with others) in the **revisions** branch of this repository. I am going to sit on it for a couple days before merging it into master (just to make sure I don't want to change anything else). Please give it a try, and let me know if it works well for you.

**Comment by Rushi98** [comment]
The 'revisions' version is working fine. :100: 
Thanks for the package.
